routers :
  - global:
      hostname: "CE1"
      host: "192.168.122.144"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    interfaces:
      - name: "g1/0"
        address: "dhcp"
        no-shutdown: true
      - name: "g2/0"
        address: "dhcp"
        no-shutdown: true
      - name: "g3/0"
        address: "dhcp"
        no-shutdown: true

        
  - global:
      hostname: "PE1"
      host: "192.168.122.168"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    interfaces:
      - name: "g1/0"
        address: "10.10.10.1"
        mask: "255.255.255.0"
        no-shutdown: true
