routers :

# ------------- R2 ------------- #

  - global:
      hostname: "R2"
      host: "192.168.122.12"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"


    interfaces:
      - name: "g1/0"
        address: "20.21.0.1"
        mask: "255.255.255.0"
        no-shutdown: true

      - name: "g2/0"
        address: "194.20.21.2"
        mask: "255.255.255.0"
        no-shutdown: true

    ospf:
      process-number: "1"
      networks:
        - subnet: "194.20.21.0"
          mask: "0.0.0.255"
          area: "0"
        - subnet: "20.21.0.0"
          mask: "0.0.255.255"
          area: "0"  


# ------------- R3 ------------- #

  - global:
      hostname: "R3"
      host: "192.168.122.13"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    interfaces:
      - name: "g1/0"
        address: "20.21.1.1"
        mask: "255.255.255.0"
        no-shutdown: true

      - name: "g2/0"
        address: "194.20.22.2"
        mask: "255.255.255.0"
        no-shutdown: true

    ospf:
      process-number: "1"
      networks:
        - subnet: "194.20.22.0"
          mask: "0.0.0.255"
          area: "0"
        - subnet: "20.21.0.0"
          mask: "0.0.255.255"
          area: "0"  

# ------------- R5 ------------- #

  - global:
      hostname: "R5"
      host: "192.168.122.15"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    loopbacks:
      - number: 0
        address: "10.168.10.5"
        mask: "255.255.255.255"

    interfaces:
      - name: "g3/0"
        address: "172.26.57.1"
        mask: "255.255.255.0"
        no-shutdown: true

    ospf:
      process-number: "1"
      networks:
        - subnet: "172.0.0.0"
          mask: "0.255.255.255"
          area: "0"
        - subnet: "10.168.0.0"
          mask: "0.0.255.255"
          area: "0"
  
# ------------- R6 ------------- #

  - global:
      hostname: "R6"
      host: "192.168.122.16"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    loopbacks:
      - number: 0
        address: "10.168.10.6"
        mask: "255.255.255.255"

    interfaces:
      - name: "g3/0"
        address: "172.26.67.1"
        mask: "255.255.255.0"
        no-shutdown: true

    ospf:
      process-number: "1"
      networks:
        - subnet: "172.0.0.0"
          mask: "0.255.255.255"
          area: "0"
        - subnet: "10.168.0.0"
          mask: "0.0.255.255"
          area: "0"

# ------------- R7 ------------- #

  - global:
      hostname: "R7"
      host: "192.168.122.17"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    loopbacks:
      - number: 0
        address: "10.168.10.7"
        mask: "255.255.255.255"

    interfaces:
      - name: "g1/0"
        address: "172.26.67.2"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g2/0"
        address: "172.26.57.2"
        mask: "255.255.255.0"
        no-shutdown: true

    ospf:
      process-number: "1"
      networks:
        - subnet: "172.0.0.0"
          mask: "0.255.255.255"
          area: "0"
        - subnet: "10.168.0.0"
          mask: "0.0.255.255"
          area: "0"
  

