routers :
  - global:
      hostname: "CE1"
      host: "192.168.122.144"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    loopbacks:
      - number: 0
        address: "1.1.1.1"
        mask: "255.255.255.255"
    
    interfaces:
      - name: "g1/0"
        address: "192.168.0.1"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g2/0"
        address: "192.168.0.2"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g3/0"
        address: "192.168.0.3"
        mask: "255.255.255.0"
        no-shutdown: true

    dhcp: 
      excluded-address-min: "192.168.0.1"
      excluded-address-max: "192.168.0.50"
      pool-name: "ApertureDHCP"
      subnet: "192.168.0.0"
      subnet-mask: "255.255.255.0"
      default-router: "192.168.0.1"
      dns-server: "192.168.0.1"

    osfp:
      process-number: "1"
      networks:
        - subnet: "192.168.1.0"
        - mask: "0.0.0.255"
        - area: "0"



  - global:
      hostname: "PE1"
      host: "192.168.122.168"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    loopbacks:
      - number: 0
        address: "2.2.2.2"
        mask: "255.255.255.255"
  
    interfaces:
      - name: "g1/0"
        address: "10.10.10.1"
        mask: "255.255.255.0"
        no-shutdown: true
