routers :

# ------------- R1 (CE1 Kelebulc)------------- #

  - global:
      hostname: "R1"
      host: "192.168.122.11"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    dhcp: 
      excluded-address-min: "172.16.1.1"
      excluded-address-max: "172.16.1.50"
      pool-name: "KelebulcDHCP"
      subnet: "172.16.1.0"
      subnet-mask: "255.255.255.0"
      default-router: "172.16.1.254"
      dns-server: "172.16.1.254"


    interfaces:
      - name: "g1/0"
        address: "172.16.1.254"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g2/0"
        address: "11.11.16.1"
        mask: "255.255.255.0"
        no-shutdown: true

# ------------- R2 (CE1 Aperture) ------------- #

  - global:
      hostname: "R2"
      host: "192.168.122.12"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    interfaces:
      - name: "g1/0"
        address: "172.16.1.254"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g2/0"
        address: "11.11.26.2"
        mask: "255.255.255.0"
        no-shutdown: true

    dhcp: 
      excluded-address-min: "172.16.1.1"
      excluded-address-max: "172.16.1.50"
      pool-name: "ApertureDHCP"
      subnet: "172.16.1.0"
      subnet-mask: "255.255.255.0"
      default-router: "172.16.1.254"
      dns-server: "172.16.1.254"

# ------------- R3 (CE2 Aperture) ------------- #

  - global:
      hostname: "R3"
      host: "192.168.122.13"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    interfaces:
      - name: "g1/0"
        address: "172.16.2.254"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g2/0"
        address: "11.11.35.3"
        mask: "255.255.255.0"
        no-shutdown: true

    dhcp: 
      excluded-address-min: "172.16.2.1"
      excluded-address-max: "172.16.2.50"
      pool-name: "ApertureDHCP"
      subnet: "172.16.2.0"
      subnet-mask: "255.255.255.0"
      default-router: "172.16.2.254"
      dns-server: "172.16.2.254"

# ------------- R4 (CE2 Kelebulc) ------------- #

  - global:
      hostname: "R4"
      host: "192.168.122.14"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    dhcp: 
      excluded-address-min: "172.16.2.1"
      excluded-address-max: "172.16.2.50"
      pool-name: "Kelebulc"
      subnet: "172.16.2.0"
      subnet-mask: "255.255.255.0"
      default-router: "172.16.2.254"
      dns-server: "172.16.2.254"

    interfaces:
      - name: "g1/0"
        address: "172.16.2.254"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g2/0"
        address: "11.11.45.4"
        mask: "255.255.255.0"
        no-shutdown: true

# ------------- R5 (PE1)------------- #

  - global:
      hostname: "R5"
      host: "192.168.122.15"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    loopbacks:
      - number: 0
        address: "10.1.1.5"
        mask: "255.255.255.255"

    interfaces:
      - name: "g3/0"
        address: "10.10.57.5"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g2/0"
        address: "11.11.45.5"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g1/0"
        address: "11.11.35.5"
        mask: "255.255.255.0"
        no-shutdown: true

# ------------- R6 (PE2)------------- #

  - global:
      hostname: "R6"
      host: "192.168.122.16"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    loopbacks:
      - number: 0
        address: "10.1.1.6"
        mask: "255.255.255.255"

    interfaces:
      - name: "g3/0"
        address: "10.10.67.6"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g2/0"
        address: "11.11.16.6"
        no-shutdown: true
      - name: "g1/0"
        address: "11.11.26.6"
        mask: "255.255.255.0"
        no-shutdown: true

# ------------- R7 (P) ------------- #

  - global:
      hostname: "R7"
      host: "192.168.122.17"
      username: "antoine"
      password: "cisco"
      enable-password: "cisco"

    loopbacks:
      - number: 0
        address: "10.1.1.7"
        mask: "255.255.255.255"

    interfaces:
      - name: "g1/0"
        address: "10.10.67.7"
        mask: "255.255.255.0"
        no-shutdown: true
      - name: "g2/0"
        address: "10.10.57.7"
        mask: "255.255.255.0"
        no-shutdown: true

  

